### ISSUE TITLE
`lerna bootstrap` removed in lerna v7

### ISSUE THREAD

**Issue by durw4rd** [tanben/sample-microfrontend#1]
With Lerna >=v7.x, the `lerna bootstrap` is no longer supported (https://lerna.js.org/docs/legacy-package-management). 
I was able to start the application while skipping the `lerna bootstrap` command & by removing `"useWorkspaces": true,` from lerna.json.

**Comment by tanben** [comment]
I've verified your findings and made the changes, thank you for looking into this.
